/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.12.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    val artifactoryUsername: String? = System.getenv("ARTIFACTORY_PRIVATE_USERNAME")
        ?: providers.gradleProperty("artifactoryUsername").orNull
    val artifactoryPassword: String? = System.getenv("ARTIFACTORY_PRIVATE_PASSWORD")
        ?: providers.gradleProperty("artifactoryPassword").orNull
    repositories {
        maven {
            url = uri("https://repox.jfrog.io/repox/sonarsource")
            if (artifactoryUsername != null && artifactoryPassword != null) {
                credentials {
                    username = artifactoryUsername
                    password = artifactoryPassword
                }
            }
        }
    }
}

rootProject.name = "sonar-rust-plugin"

include("sonar-rust-plugin")
include("analyzer")
include("e2e")
