[package]
name = "analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
tree-sitter = "0.25.1"
tree-sitter-rust = "0.23.2"
