[target.aarch64-apple-darwin]
linker = "arm64e-apple-darwin21.1-clang"
ar = "arm64e-apple-darwin21.1-ar"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-unknown-linux-gnu-gcc"

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
